#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1442180504                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : #assets/appicon.png                       # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Gratuity                                  # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : #$0.99                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Tip Tracker

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Derik Malcolm
your_link                                 :
your_city                                 : Lockport
email_address                             : DerikMalcolm@icloud.com
facebook_username                         :
instagram_username                        :
twitter_username                          : Fr0mDerik
github_username                           : FromDerik
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :
  - title                                 : Keep Track
    description                           : See how much you've made on a certain day, week, and month.
    fontawesome_icon_name                 : calendar-alt

  - title                                 : Synchronized using iCloud
    description                           : Your data is synchronized between your devices using Apple's iCloud.
    fontawesome_icon_name                 : cloud

  - title                                 : Offline Support
    description                           : Gratuity is meant to be used on the road. All your data is stored offline using Apple's Core Data and will be synchronised whenever possible.
    fontawesome_icon_name                 : road

# Theme Settings
topbar_color                              : "#2075ff"
topbar_transparency                       : 0
topbar_title_color                        : "#ffffff"

# cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_top_color                   : "#2075ff"
cover_overlay_bottom_color                : "#ffffff"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#2075ff"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#2075ff"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
